import type { Product } from "@/types/product"

export const mockProducts: Record<string, Product[]> = {
  smartphones: [
    {
      id: "1",
      title: "iPhone 15 Pro Max",
      price: 180000,
      salePrice: 165000,
      image: "/iphone-15-pro-max.png",
      category: "Smartphones",
      manufacturer: "Apple",
      badge: "New",
      features: {
        Display: "6.7-inch Super Retina XDR",
        Processor: "A17 Pro chip",
        "Rear Camera": "48MP Main + 12MP Ultra Wide",
        Battery: "4441 mAh",
      },
    },
    {
      id: "2",
      title: "Samsung Galaxy S24 Ultra",
      price: 170000,
      salePrice: 155000,
      image: "/samsung-galaxy-s24-ultra.png",
      category: "Smartphones",
      manufacturer: "Samsung",
      features: {
        Display: "6.8-inch Dynamic AMOLED 2X",
        Processor: "Snapdragon 8 Gen 3",
        "Rear Camera": "200MP Main + 50MP Periscope",
        Battery: "5000 mAh",
      },
    },
    {
      id: "3",
      title: "Google Pixel 8 Pro",
      price: 140000,
      image: "/google-pixel-8-pro-smartphone.jpg",
      category: "Smartphones",
      manufacturer: "Google",
      features: {
        Display: "6.7-inch LTPO OLED",
        Processor: "Google Tensor G3",
        "Rear Camera": "50MP Main + 48MP Ultra Wide",
        Battery: "5050 mAh",
      },
    },
    {
      id: "4",
      title: "OnePlus 12",
      price: 120000,
      salePrice: 110000,
      image: "/oneplus-12-smartphone.jpg",
      category: "Smartphones",
      manufacturer: "OnePlus",
      features: {
        Display: "6.82-inch LTPO AMOLED",
        Processor: "Snapdragon 8 Gen 3",
        "Rear Camera": "50MP Main + 64MP Periscope",
        Battery: "5400 mAh",
      },
    },
  ],
  laptops: [
    {
      id: "5",
      title: "MacBook Pro 16-inch M3 Max",
      price: 450000,
      salePrice: 420000,
      image: "/macbook-pro-16-inch-laptop.jpg",
      category: "Laptops",
      manufacturer: "Apple",
      badge: "Pro",
      features: {
        Display: "16.2-inch Liquid Retina XDR",
        Processor: "Apple M3 Max chip",
        Graphics: "40-core GPU",
        Battery: "Up to 22 hours",
      },
    },
    {
      id: "6",
      title: "Dell XPS 15 OLED",
      price: 280000,
      image: "/dell-xps-15-oled-laptop.jpg",
      category: "Laptops",
      manufacturer: "Dell",
      features: {
        Display: "15.6-inch 3.5K OLED",
        Processor: "Intel Core i7-13700H",
        Graphics: "NVIDIA RTX 4070",
        Battery: "86 Wh",
      },
    },
    {
      id: "7",
      title: "ASUS ROG Zephyrus G16",
      price: 320000,
      salePrice: 295000,
      image: "/asus-rog-zephyrus-gaming-laptop.jpg",
      category: "Laptops",
      manufacturer: "ASUS",
      badge: "Gaming",
      features: {
        Display: "16-inch 2.5K 240Hz",
        Processor: "AMD Ryzen 9 7940HS",
        Graphics: "NVIDIA RTX 4080",
        Battery: "90 Wh",
      },
    },
  ],
  accessories: [
    {
      id: "8",
      title: "AirPods Pro (2nd generation)",
      price: 35000,
      salePrice: 32000,
      image: "/airpods-pro-wireless-earbuds.jpg",
      category: "Accessories",
      manufacturer: "Apple",
      features: {
        Type: "Wireless Earbuds",
        "Noise Cancellation": "Active",
        "Battery Life": "Up to 6 hours",
        Connectivity: "Bluetooth 5.3",
      },
    },
    {
      id: "9",
      title: "Logitech MX Master 3S",
      price: 15000,
      image: "/logitech-mx-master-3s-wireless-mouse.jpg",
      category: "Accessories",
      manufacturer: "Logitech",
      features: {
        Type: "Wireless Mouse",
        DPI: "Up to 8000",
        Battery: "Up to 70 days",
        Connectivity: "Bluetooth/USB-C",
      },
    },
    {
      id: "10",
      title: "Samsung 49-inch Odyssey G9",
      price: 180000,
      salePrice: 165000,
      image: "/samsung-odyssey-g9-curved-gaming-monitor.jpg",
      category: "Accessories",
      manufacturer: "Samsung",
      badge: "Ultra Wide",
      features: {
        Size: "49-inch Curved",
        Resolution: "5120 x 1440",
        "Refresh Rate": "240Hz",
        Panel: "VA QLED",
      },
    },
  ],
}
